### ISSUE TITLE
Request: Sorting

### ISSUE THREAD

**Issue by jmeyer1980** [CLJunge/Spawn.HDT.DustUtility#1]
It would be very nice if we could (or the addon would automatically) sort the cards by class and then by mana cost instead of dust. I find it very tedious that I have to search for each card.

It would also be cool if we could select which cards we wish to dust and have the addon do it for us... but that might be a bit much. Lol.

**Comment by CLJunge** [comment]
I'll just implement a customizable sort order, so you can set it to whatever you need.

And i'll try to figure out how i can implement your second request :)

**Comment by CLJunge** [comment]
Implemented customizable sorting in release 1.4. If there are any issues with the release, please create a new issue here.

I thought about your second request and think that it is to risky to implement such functionality If something goes wrong and the wrong cards are being disenchanted, there is no way to get them back.

**Comment by CLJunge** [comment]
Found a bug and removed release 1.4 until its fixed.

**Comment by jmeyer1980** [comment]
Thank you very much for your work. I can completely understand the risk with mass dusting. I look forward to seeing the changes after you fix the bug =)

**Comment by CLJunge** [comment]
Bug is fixed. Let me know if you have any other requests :)
