### ISSUE TITLE
"Auto Disenchanting"

### ISSUE THREAD

**Issue by Fonjask** [CLJunge/Spawn.HDT.DustUtility#3]
> With the setting Auto Disenchanting enabled, the plugin can automatically disenchant the current card selection by emulating the mouse cursor. (Works like the old HDT export feature)

Is this still in this plugin? If so, where is the setting? I can't find it.

**Comment by CLJunge** [comment]
I'm sorry, I forgot to remove this part from the README file since this feature is planned for a future update.
